spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fengru?serverTimezone=GMT%2B8
    username: root
    password: Lvchaofan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  hibernate:
    format_sql: true

mybatis-plus:
  configuration:
    # 打印出具体的sql语句hb
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.hibernate.SQL: debug
140:
  143:
    170:
      37:
server:
  port: 8080

